title: Default Page

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            type: textarea
            fields:

  sidebar:
    width: 1/3
    sections:
      meta:
        type: fields
        fields:
          description:
            label: Meta Description
            type: text
          metaTitle:
            label: Meta title
            type: text
          toggle:
            label: Google index
            type: toggle
            text: Index this page?
      image:
        label: Image
        type: files
        layout: cards
        max: 1

